FROM oracleclient:latest

ARG UID=1001
RUN echo "Building image with \"worker\" user ID: ${UID}"
RUN useradd --create-home --shell /bin/bash worker --uid ${UID}

# Copy easyaccess and compile:
WORKDIR /home/worker
COPY --chown=worker:worker ./easyaccess ./easyaccess
WORKDIR /home/worker/easyaccess
RUN python3 setup.py install
