FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y  \
    python3-pip         \
    libaio1             \
    wget                \
    imagemagick         \
    stiff               \
    mpich               \
    libopenmpi-dev      \
    openssh-client      \
    unzip

RUN rm -rf /var/lib/apt/lists/*

# ORACLE DB Client installation (https://oracle.github.io/odpi/doc/installation.html#oracle-instant-client-zip)
RUN mkdir -p /opt/oracle
ADD https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip /opt/oracle/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip
RUN \
  cd /opt/oracle && \
  unzip instantclient-basic-linux.x64-19.6.0.0.0dbru.zip && \
  echo /opt/oracle/instantclient_19_6 > /etc/ld.so.conf.d/oracle-instantclient.conf && \
  ldconfig
